apiVersion: v1
kind: Service
metadata:
  name: secret-validator-service
  labels:
    app: secret-validator
spec:
  type: NodePort
  selector:
    app: secret-validator
  ports:
  - protocol: TCP
    port: 5000
    targetPort: 5000
    nodePort: 30500
    name: http
